import React from 'react';
import { ScrollView, Text, View, useWindowDimensions } from 'react-native';
import { BottomSheet } from '../BottomSheet';
import { Button } from '../Button';
import { styles } from './styles';

interface PolicyConsentSheetProps {
  isVisible: boolean;
  isLoading?: boolean;
  onAccept: () => void;
}

const CONSENT_SECTIONS = [
  {
    title: 'Collection and Use of Information',
    body: [
      'AthMech may collect, store, process, analyse, transfer, share and otherwise use information provided by you or generated through your use of the Services, including:',
    ],
    bullets: [
      'videos and recordings',
      'audio recordings',
      'photographs and images',
      'stump calibration images',
      'session recordings',
      'delivery clips and segmented videos',
      'athlete, coach and academy information',
      'player profile information',
      'location information',
      'device information',
      'operating system information',
      'usage and activity information',
      'camera, microphone and notification permissions',
      'performance information',
      'biometric and biomechanical information',
      'pose estimation data',
      'human detection data',
      'ball tracking data',
      'event detection data',
      'analytics',
      'rankings',
      'reports',
      'athlete profiles',
      'any other information collected, generated or derived through the Services',
    ],
  },
  {
    title: 'Artificial Intelligence and Analytics',
    body: [
      'You authorise AthMech to analyse and process content and information using artificial intelligence, machine learning, computer vision, analytics and related technologies.',
      'AthMech may use collected information to:',
    ],
    bullets: [
      'identify and track players, coaches, balls, equipment and sporting actions',
      'generate biomechanics and performance analytics',
      'create reports, rankings and athlete profiles',
      'improve products and services',
      'develop, train and improve artificial intelligence systems',
      'create datasets, benchmarks and research assets',
      'support future products and technologies',
    ],
  },
  {
    title: 'Generated Content and Derived Data',
    body: [
      'You acknowledge that AthMech may generate additional content and information from material submitted to the Services, including:',
    ],
    bullets: [
      'delivery clips',
      'session clips',
      'pose outputs',
      'tracking outputs',
      'trajectories',
      'event detections',
      'analytics',
      'reports',
      'labels',
      'annotations',
      'rankings',
      'athlete profiles',
      'datasets',
      'benchmarks',
      'machine learning assets',
      'artificial intelligence assets',
      'other outputs generated by AthMech systems',
    ],
    after: [
      'You acknowledge and agree that such Generated Content and Derived Data are valuable AthMech assets and may be retained, analysed, used, commercialised, licensed, transferred and otherwise exploited by AthMech, including after account closure, deletion of content or termination of your use of the Services, to the maximum extent permitted by applicable law.',
    ],
  },
  {
    title: 'Coach, Academy and Group Session Visibility',
    body: [
      'CrickRoo allows players to participate in individual and group activities and allows players to connect with coaches, academies, clubs, schools and other sporting organisations.',
      'You acknowledge and agree that:',
    ],
    bullets: [
      'coaches, academies, clubs, schools and authorised sporting organisations associated with a player may access player sessions, videos, recordings, delivery clips, analytics, reports, athlete profiles and related performance information',
      'such access may include sessions conducted independently by a player and sessions conducted outside academy, club or coach-supervised activities',
      'group sessions may include multiple participants',
      'information relating to multiple participants may appear in the same session, recording, clip, report or analytics output',
      'authorised coaches, academies, clubs and schools associated with participants may be able to view information relating to other participants appearing in those sessions',
    ],
    after: [
      'For example, where a player linked to a coach participates in a group session with another player, the linked coach may be able to view that session and may see footage, audio, analytics and performance information relating to other participants appearing in the session.',
      'By participating in group sessions, being tagged in sessions, appearing in recordings or linking with a coach, academy, club or school, you consent to such visibility and access.',
    ],
  },
  {
    title: 'Opportunities, Recommendations and Commercial Activities',
    body: [
      'AthMech may use information collected through the Services to identify, facilitate, recommend or provide:',
    ],
    bullets: [
      'coaching opportunities',
      'academy opportunities',
      'recruitment opportunities',
      'scouting opportunities',
      'scholarships',
      'sponsorship opportunities',
      'endorsement opportunities',
      'athlete development opportunities',
      'sporting opportunities',
      'equipment recommendations',
      'commercial offers',
      'partner offers',
      'future products and services',
    ],
  },
  {
    title: 'Marketing and Promotional Rights',
    body: [
      'You grant AthMech a worldwide, perpetual, irrevocable, transferable, sublicensable and royalty-free right to use, reproduce, modify, distribute, publish, display and otherwise utilise content, recordings, images, videos, audio, analytics, athlete profiles, reports, testimonials and related information for:',
    ],
    bullets: [
      'marketing',
      'advertising',
      'promotion',
      'public relations',
      'investor relations',
      'research',
      'education',
      'demonstrations',
      'publications',
      'other business purposes, subject to applicable law',
    ],
  },
  {
    title: 'Account Closure and Retention',
    body: [
      'You acknowledge that account closure, account deletion or content removal does not necessarily require AthMech to delete, destroy or cease using information, Generated Content, Derived Data, anonymised information, aggregated information, datasets, analytics, research assets, benchmarks, machine learning assets, artificial intelligence assets, historical records or business records.',
      'AthMech may retain, archive, anonymise, analyse and continue to use such information to the extent permitted by applicable law.',
    ],
  },
  {
    title: 'Minors',
    body: [
      'If you are under the age required to provide consent in your jurisdiction, you confirm that a parent, guardian, academy, club, school or other authorised representative has reviewed and accepted this Agreement on your behalf.',
    ],
  },
];

const renderSection = (section: (typeof CONSENT_SECTIONS)[number]) => (
  <View key={section.title} style={styles.section}>
    <Text style={styles.sectionTitle}>{section.title}</Text>
    {section.body.map(paragraph => (
      <Text key={paragraph} style={styles.paragraph}>
        {paragraph}
      </Text>
    ))}
    {section.bullets?.map(item => (
      <Text key={item} style={styles.bullet}>
        {'\u2022'} {item}
      </Text>
    ))}
    {section.after?.map(paragraph => (
      <Text key={paragraph} style={styles.paragraph}>
        {paragraph}
      </Text>
    ))}
  </View>
);

const ConsentDetails: React.FC = () => (
  <View style={styles.contentCard}>
    <Text style={styles.introText}>
      By creating an account, accessing, uploading content to, recording
      sessions through, or otherwise using CrickRoo and related services
      operated by AthMech Pty Ltd (ACN 690 049 864) ("AthMech"), you acknowledge
      and agree that:
    </Text>
    {CONSENT_SECTIONS.map(renderSection)}
  </View>
);

export const PolicyConsentSheet: React.FC<PolicyConsentSheetProps> = ({
  isVisible,
  isLoading = false,
  onAccept,
}) => {
  const { height } = useWindowDimensions();
  const sheetHeight = Math.round(height * 0.92);

  return (
    <BottomSheet
      isVisible={isVisible}
      title="Terms and conditions"
      onClose={() => {}}
      showHandle
      closeOnBackdrop={false}
      showCloseButton={false}
      sheetContainerStyle={{ height: sheetHeight }}
    >
      <View style={styles.contentRoot}>
        <View style={styles.introContainer} />

        <ScrollView
          style={styles.scroll}
          contentContainerStyle={styles.scrollContent}
          showsVerticalScrollIndicator={false}
        >
          <ConsentDetails />
        </ScrollView>

        <View style={styles.footerContent}>
          <Button
            label="I Agree"
            onPress={onAccept}
            variant="primary"
            loading={isLoading}
            disabled={isLoading}
          />
        </View>
      </View>
    </BottomSheet>
  );
};
