import { StyleSheet } from 'react-native';
import { colors } from '../../../theme/colors';
import { typography } from '../../../theme/typography';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.neutrals.bg,
  },
  header: {
    height: 64,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.neutrals.card_border_15,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: colors.glass.black_40,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: -8,
  },
  backIcon: {
    width: 24,
    height: 24,
    tintColor: colors.neutrals.white,
  },
  headerTitle: {
    ...typography.headers.h4.semiBold,
    color: colors.neutrals.white,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 40,
  },
  sectionLabel: {
    ...typography.body.b2.semiBold,
    color: colors.neutrals[70],
    marginBottom: 16,
    textTransform: 'uppercase',
  },
  videoCard: {
    width: '100%',
    aspectRatio: 1 / 1,
    borderRadius: 5,
    overflow: 'hidden',
    backgroundColor: colors.neutrals.card_bg,
  },
  zoomableVideo: {
    ...StyleSheet.absoluteFillObject,
  },
  videoThumbnail: {
    width: '100%',
    height: '100%',
    position: 'absolute',
  },
  videoOverlay: {
    ...StyleSheet.absoluteFill,
    padding: 20,
    backgroundColor: colors.glass.black_30,
  },
  leftColumn: {
    position: 'absolute',
    top: 16,
    left: 16,
    gap: 8,
    alignItems: 'flex-start',
  },
  typeBadge: {
    backgroundColor: colors.neutrals.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 500,
  },
  typeText: {
    ...typography.captions.c1.semiBold,
    fontSize: 14,
    color: colors.neutrals.deep_black,
  },
  ballBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.glass.black_50,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 500,
    gap: 4,
  },
  ballIcon: {
    width: 16,
    height: 16,
    tintColor: colors.neutrals.white,
  },
  ballText: {
    ...typography.captions.c1.semiBold,
    fontSize: 14,
    color: colors.neutrals[90],
  },
  favButton: {
    position: 'absolute',
    top: 16,
    right: 16,
    padding: 8,
    borderRadius: 500,
    backgroundColor: colors.glass.black_60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomButton: {
    position: 'absolute',
    top: 70,
    right: 16,
    padding: 8,
    borderRadius: 500,
    backgroundColor: colors.glass.black_60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  zoomLevelBadge: {
    position: 'absolute',
    top: 116,
    right: 16,
    minWidth: 48,
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 500,
    backgroundColor: colors.glass.black_60,
  },
  zoomLevelText: {
    ...typography.captions.c1.semiBold,
    color: colors.neutrals.white,
  },
  favIcon: {
    width: 28,
    height: 28,
    tintColor: colors.neutrals.white,
  },
  centerControl: {
    ...StyleSheet.absoluteFill,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playCenter: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.glass.black_60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  playIcon: {
    width: 32,
    height: 32,
    aspectRatio: 1 / 1,
    tintColor: colors.neutrals.white,
    marginLeft: 4,
  },
  bottomControls: {
    position: 'absolute',
    bottom: 16,
    left: 16,
    right: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
  },
  timeText: {
    ...typography.captions.c1.medium,
    color: colors.neutrals.white,
    backgroundColor: colors.glass.black_60,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 500,
  },
  fullscreenButton: {
    padding: 8,
    borderRadius: 500,
    backgroundColor: colors.glass.black_60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  extendIcon: {
    width: 28,
    height: 28,
    tintColor: colors.neutrals.white,
  },
  fullscreenIcon: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: colors.neutrals.white,
    borderRadius: 4,
  },
  progressBarBg: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 4,
    backgroundColor: colors.glass.white_10,
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.primary.main,
    borderRadius: 2,
    width: '40%',
  },
  progressKnob: {
    position: 'absolute',
    left: '40%',
    bottom: 0,
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: colors.primary[70],
    transform: [{ translateX: -3 }],
  },
  deliveriesList: {
    flex: 1,
  },
  gridDeliveries: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  gridRow: {
    justifyContent: 'flex-start',
    gap: 12,
    marginBottom: 12,
  },
  fixedSection: {
    paddingHorizontal: 20,
    paddingTop: 16,
  },
  deliveriesHeader: {
    ...typography.body.b2.semiBold,
    color: colors.neutrals[70],
    marginBottom: 16,
    textTransform: 'uppercase',
    marginTop: 24,
    paddingHorizontal: 20,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: colors.neutrals.bg,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorContainer: {
    flex: 1,
    backgroundColor: colors.neutrals.bg,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    ...typography.body.b1.medium,
    color: colors.neutrals.white,
    marginBottom: 20,
    textAlign: 'center',
  },
  retryButton: {
    paddingHorizontal: 24,
    paddingVertical: 12,
    backgroundColor: colors.primary.main,
    borderRadius: 12,
  },
  retryButtonText: {
    ...typography.body.b2.semiBold,
    color: colors.neutrals.black,
  },
  emptyContainer: {
    flex: 1,
    backgroundColor: colors.neutrals.bg,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyText: {
    ...typography.body.b1.medium,
    color: colors.neutrals[70],
    textAlign: 'center',
    marginTop: 16,
  },
  loadingMoreSpinner: {
    marginVertical: 16,
  },
});
